sine:
	clang++ -std=c++11 -Wall -Wno-c++11-extensions -I../Library/Include SineTable.cpp
	./a.out
	rm ./a.out

cosine:
	clang++ -std=c++11 -Wall -Wno-c++11-extensions -I../Library/Include CosineTable.cpp
	./a.out
	rm ./a.out

arccosine:
	clang++ -std=c++11 -Wall -Wno-c++11-extensions -I../Library/Include ArcCosineTable.cpp
	./a.out
	rm ./a.out

constants:
	clang++ -std=c++11 -Wall -Wno-c++11-extensions -I../Library/Include Constants.cpp
	./a.out
	rm ./a.out
